Update vmsizes.py for newer Azure API endpoint
ComputeCanada/magic_castle pull request #294
Opened 2024-03-12 14:28 UTC by ocaisa

2024-03-12 17:51 UTC, cmd-ntrf requested changes

2024-03-12 17:51 UTC, cmd-ntrf commented on utils/azure/vmsizes/vmsizes.py
> +                    }
The value extraction can be simplified by defining a dictionary first:
```python
                    caps = { el["name"]:el["value"] for el in item["capabilities"] }
                    value = {
                        "vcpus": int(caps.get("vCPUsAvailable", caps["vCPUs"])),
                        "ram":   int(float(caps.get("MemoryGB"))* 1000),
                        "gpus":  int(caps.get("GPUs", 0))
                    }
```

This also fixes the case where for some VMs, `vCPUs != vCPUsAvailable`.

2024-03-12 17:51 UTC, cmd-ntrf commented on utils/azure/vmsizes/vmsizes.py
> +    return result_value
No longer needed

2024-03-12 17:51 UTC, cmd-ntrf commented on utils/azure/vmsizes/vmsizes.py
> +        help="az account get-access-token --resource https://management.azure.com",
Subscription id can be retrieve with `az account show`

2024-03-26 19:17 UTC, merged

2024-03-26 22:08 UTC, ocaisa commented
Apologies for not getting back to this!